Demo1:
	gcc -o pthread_doc pthread_doc.c -DDemo_1 -lpthread
	./pthread_doc

Demo2:
	gcc -o pthread_doc pthread_doc.c -DDemo_2 -lpthread
	./pthread_doc

Demo3:
	gcc -o pthread_doc pthread_doc.c -DDemo_3 -lpthread
	./pthread_doc

Demo4:
	gcc -o pthread_doc pthread_doc.c -DDemo_4 -lpthread
	./pthread_doc

Demo5:
	gcc -o pthread_doc pthread_doc.c -DDemo_5 -lpthread
	./pthread_doc

Demo6:
	gcc -o pthread_doc pthread_doc.c -DDemo_6 -lpthread
	./pthread_doc

Demo7:
	gcc -o pthread_doc pthread_doc.c -DDemo_7 -lpthread
	./pthread_doc

clean:
	rm -rf pthread_doc

PHONY:
	echo "Unknown option. Enter again."